# Generated by Django 4.2.5 on 2023-10-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agents_to_manage',
            field=models.ManyToManyField(blank=True, null=True, related_name='my_agents', to='account.agentprofile', verbose_name='My Agents'),
        ),
    ]
