# Generated by Django 4.2.5 on 2023-10-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_agents_to_manage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
