# Generated by Django 4.2.5 on 2023-10-04 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='account_type',
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='agent_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.agenttype'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='code',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='district',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='district'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='idtype',
            field=models.CharField(blank=True, choices=[('NRC', 'NRC'), ('Passport', 'Passport'), ('Drivers License', 'Drivers License')], max_length=300, verbose_name='ID type'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='phonenumber',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='province',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='province'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
