# Generated by Django 4.2.5 on 2023-10-03 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FispTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transAdt', models.CharField(max_length=150)),
                ('numberOfFarmers', models.IntegerField()),
                ('isSuccess', models.BooleanField(default=False)),
                ('isDeposited', models.BooleanField(default=False)),
                ('transAmount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('totalCommis', models.DecimalField(decimal_places=2, max_digits=100)),
                ('transCommisAgent', models.DecimalField(decimal_places=2, max_digits=100)),
                ('transOldBalance', models.DecimalField(decimal_places=2, max_digits=100)),
                ('transNewBalance', models.DecimalField(decimal_places=2, max_digits=100)),
                ('transNewComBalance', models.DecimalField(decimal_places=2, max_digits=100)),
                ('transOldComBalance', models.DecimalField(decimal_places=2, max_digits=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('leadernumber', models.CharField(max_length=50)),
                ('depositer', models.CharField(max_length=50)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.agentprofile')),
            ],
        ),
    ]
