# Generated by Django 4.2.5 on 2023-10-03 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_fisptransaction_transref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fisptransaction',
            name='transRef',
        ),
    ]
