# Generated by Django 4.2.5 on 2023-10-04 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('transactions', '0003_remove_fisptransaction_transref'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('agent_given', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.agentprofile')),
            ],
        ),
    ]
