# Generated by Django 4.2.5 on 2023-10-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_fisptransaction_transref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisptransaction',
            name='isDeposited',
            field=models.BooleanField(default=False),
        ),
    ]
