# Generated by Django 4.2.5 on 2023-10-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_fisptransaction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fisptransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='fisptransaction',
            index=models.Index(fields=['agent_id'], name='transaction_agent_i_5fec8d_idx'),
        ),
        migrations.AddIndex(
            model_name='fisptransaction',
            index=models.Index(fields=['created_at'], name='transaction_created_31e62c_idx'),
        ),
    ]
